Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controller\\AdminController",
            "name": "AdminController",
            "summary": "Contr\u00F4leur\u0020d\u0027administration.",
            "url": "classes/App-Controller-AdminController.html"
        },                {
            "fqsen": "\\App\\Controller\\AdminController\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "",
            "url": "classes/App-Controller-AdminController.html#method_insert"
        },                {
            "fqsen": "\\App\\Controller\\AdminController\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/App-Controller-AdminController.html#method_update"
        },                {
            "fqsen": "\\App\\Controller\\AdminController\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/App-Controller-AdminController.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\AdminController\u003A\u003AtestAction\u0028\u0029",
            "name": "testAction",
            "summary": "",
            "url": "classes/App-Controller-AdminController.html#method_testAction"
        },                {
            "fqsen": "\\App\\Controller\\ErrorController",
            "name": "ErrorController",
            "summary": "Contr\u00F4leur\u0020de\u0020gestion\u0020des\u0020erreurs.",
            "url": "classes/App-Controller-ErrorController.html"
        },                {
            "fqsen": "\\App\\Controller\\ErrorController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/App-Controller-ErrorController.html#method_show"
        },                {
            "fqsen": "\\App\\Controller\\ListeProduitsController",
            "name": "ListeProduitsController",
            "summary": "Contr\u00F4leur\u0020Symfony\u0020g\u00E9rant\u0020l\u0027affichage\u0020et\u0020la\u0020r\u00E9cup\u00E9ration\u0020des\u0020donn\u00E9es\nli\u00E9es\u0020aux\u0020produits\u0020et\u0020aux\u0020distributeurs.",
            "url": "classes/App-Controller-ListeProduitsController.html"
        },                {
            "fqsen": "\\App\\Controller\\ListeProduitsController\u003A\u003Aliste\u0028\u0029",
            "name": "liste",
            "summary": "",
            "url": "classes/App-Controller-ListeProduitsController.html#method_liste"
        },                {
            "fqsen": "\\App\\Controller\\ListeProduitsController\u003A\u003Alistedistributeur\u0028\u0029",
            "name": "listedistributeur",
            "summary": "",
            "url": "classes/App-Controller-ListeProduitsController.html#method_listedistributeur"
        },                {
            "fqsen": "\\App\\Controller\\ListeProduitsController\u003A\u003Aeager\u0028\u0029",
            "name": "eager",
            "summary": "",
            "url": "classes/App-Controller-ListeProduitsController.html#method_eager"
        },                {
            "fqsen": "\\App\\Controller\\ListeProduitsController\u003A\u003AapiTest\u0028\u0029",
            "name": "apiTest",
            "summary": "",
            "url": "classes/App-Controller-ListeProduitsController.html#method_apiTest"
        },                {
            "fqsen": "\\App\\Controller\\MailController",
            "name": "MailController",
            "summary": "Contr\u00F4leur\u0020permettant\u0020l\u0027envoi\u0020d\u0027emails.",
            "url": "classes/App-Controller-MailController.html"
        },                {
            "fqsen": "\\App\\Controller\\MailController\u003A\u003AsendEmail\u0028\u0029",
            "name": "sendEmail",
            "summary": "",
            "url": "classes/App-Controller-MailController.html#method_sendEmail"
        },                {
            "fqsen": "\\App\\Controller\\RegisterController",
            "name": "RegisterController",
            "summary": "Contr\u00F4leur\u0020d\u0027inscription\u0020des\u0020utilisateurs.",
            "url": "classes/App-Controller-RegisterController.html"
        },                {
            "fqsen": "\\App\\Controller\\RegisterController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Affiche\u0020la\u0020page\u0020d\u0027inscription.",
            "url": "classes/App-Controller-RegisterController.html#method_register"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController",
            "name": "SecurityController",
            "summary": "Contr\u00F4leur\u0020g\u00E9rant\u0020la\u0020s\u00E9curit\u00E9\u0020et\u0020l\u0027authentification.",
            "url": "classes/App-Controller-SecurityController.html"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_login"
        },                {
            "fqsen": "\\App\\Controller\\SecurityController\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "",
            "url": "classes/App-Controller-SecurityController.html#method_logout"
        },                {
            "fqsen": "\\App\\Controller\\TestController",
            "name": "TestController",
            "summary": "Contr\u00F4leur\u0020de\u0020test\u0020de\u0020l\u0027application.",
            "url": "classes/App-Controller-TestController.html"
        },                {
            "fqsen": "\\App\\Controller\\TestController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "",
            "url": "classes/App-Controller-TestController.html#method_index"
        },                {
            "fqsen": "\\App\\Controller\\TestController\u003A\u003Alist\u0028\u0029",
            "name": "list",
            "summary": "",
            "url": "classes/App-Controller-TestController.html#method_list"
        },                {
            "fqsen": "\\App\\Controller\\TestController\u003A\u003Amessage\u0028\u0029",
            "name": "message",
            "summary": "",
            "url": "classes/App-Controller-TestController.html#method_message"
        },                {
            "fqsen": "\\App\\Controller\\TestController\u003A\u003Ahello\u0028\u0029",
            "name": "hello",
            "summary": "",
            "url": "classes/App-Controller-TestController.html#method_hello"
        },                {
            "fqsen": "\\App\\Data\\ListeProduits",
            "name": "ListeProduits",
            "summary": "Classe\u0020repr\u00E9sentant\u0020une\u0020liste\u0020de\u0020produits.",
            "url": "classes/App-Data-ListeProduits.html"
        },                {
            "fqsen": "\\App\\Data\\ListeProduits\u003A\u003A\u0024mesProduits",
            "name": "mesProduits",
            "summary": "",
            "url": "classes/App-Data-ListeProduits.html#property_mesProduits"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures",
            "name": "AppFixtures",
            "summary": "Classe\u0020permettant\u0020de\u0020charger\u0020des\u0020donn\u00E9es\u0020de\u0020test\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-DataFixtures-AppFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\AppFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "M\u00E9thode\u0020appel\u00E9e\u0020lors\u0020du\u0020chargement\u0020des\u0020fixtures.",
            "url": "classes/App-DataFixtures-AppFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\JoinDistributeurFixtures",
            "name": "JoinDistributeurFixtures",
            "summary": "Classe\u0020de\u0020fixtures\u0020permettant\u0020de\u0020cr\u00E9er\u0020des\u0020relations\nentre\u0020les\u0020produits\u0020et\u0020les\u0020distributeurs.",
            "url": "classes/App-DataFixtures-JoinDistributeurFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\JoinDistributeurFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "M\u00E9thode\u0020ex\u00E9cut\u00E9e\u0020lors\u0020du\u0020chargement\u0020des\u0020fixtures.",
            "url": "classes/App-DataFixtures-JoinDistributeurFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\JoinDistributeurFixtures\u003A\u003AgetGroups\u0028\u0029",
            "name": "getGroups",
            "summary": "D\u00E9finit\u0020le\u0020groupe\u0020de\u0020fixtures\u0020auquel\u0020appartient\u0020cette\u0020classe.",
            "url": "classes/App-DataFixtures-JoinDistributeurFixtures.html#method_getGroups"
        },                {
            "fqsen": "\\App\\DataFixtures\\JoinReferenceFixtures",
            "name": "JoinReferenceFixtures",
            "summary": "Classe\u0020de\u0020fixtures\u0020permettant\u0020de\u0020cr\u00E9er\u0020et\u0020associer\ndes\u0020r\u00E9f\u00E9rences\u0020aux\u0020produits\u0020existants\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-DataFixtures-JoinReferenceFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\JoinReferenceFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "M\u00E9thode\u0020ex\u00E9cut\u00E9e\u0020lors\u0020du\u0020chargement\u0020des\u0020fixtures.",
            "url": "classes/App-DataFixtures-JoinReferenceFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\JoinReferenceFixtures\u003A\u003AgetGroups\u0028\u0029",
            "name": "getGroups",
            "summary": "D\u00E9finit\u0020le\u0020groupe\u0020de\u0020fixtures\u0020auquel\u0020appartient\u0020cette\u0020classe.",
            "url": "classes/App-DataFixtures-JoinReferenceFixtures.html#method_getGroups"
        },                {
            "fqsen": "\\App\\DataFixtures\\LoadUserData",
            "name": "LoadUserData",
            "summary": "Classe\u0020permettant\u0020de\u0020charger\u0020des\u0020utilisateurs\u0020de\u0020test\ndans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-DataFixtures-LoadUserData.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\LoadUserData\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020de\u0020la\u0020classe.",
            "url": "classes/App-DataFixtures-LoadUserData.html#method___construct"
        },                {
            "fqsen": "\\App\\DataFixtures\\LoadUserData\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "M\u00E9thode\u0020ex\u00E9cut\u00E9e\u0020lors\u0020du\u0020chargement\u0020des\u0020fixtures.",
            "url": "classes/App-DataFixtures-LoadUserData.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\LoadUserData\u003A\u003AgetGroups\u0028\u0029",
            "name": "getGroups",
            "summary": "D\u00E9finit\u0020le\u0020groupe\u0020de\u0020fixtures\u0020auquel\u0020appartient\u0020cette\u0020classe.",
            "url": "classes/App-DataFixtures-LoadUserData.html#method_getGroups"
        },                {
            "fqsen": "\\App\\DataFixtures\\LoadUserData\u003A\u003A\u0024encoder",
            "name": "encoder",
            "summary": "Service\u0020permettant\u0020de\u0020hasher\u0020les\u0020mots\u0020de\u0020passe",
            "url": "classes/App-DataFixtures-LoadUserData.html#property_encoder"
        },                {
            "fqsen": "\\App\\DataFixtures\\ProduitFixtures",
            "name": "ProduitFixtures",
            "summary": "Classe\u0020permettant\u0020de\u0020charger\u0020des\u0020produits\u0020de\u0020test\ndans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-DataFixtures-ProduitFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\ProduitFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "M\u00E9thode\u0020ex\u00E9cut\u00E9e\u0020lors\u0020du\u0020chargement\u0020des\u0020fixtures.",
            "url": "classes/App-DataFixtures-ProduitFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\UpdateImgProduitFixtures",
            "name": "UpdateImgProduitFixtures",
            "summary": "Classe\u0020de\u0020fixture\u0020permettant\u0020de\u0020mettre\u0020\u00E0\u0020jour\u0020les\u0020images\u0020des\u0020produits.",
            "url": "classes/App-DataFixtures-UpdateImgProduitFixtures.html"
        },                {
            "fqsen": "\\App\\DataFixtures\\UpdateImgProduitFixtures\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "M\u00E9thode\u0020ex\u00E9cut\u00E9e\u0020lors\u0020du\u0020chargement\u0020des\u0020fixtures.",
            "url": "classes/App-DataFixtures-UpdateImgProduitFixtures.html#method_load"
        },                {
            "fqsen": "\\App\\DataFixtures\\UpdateImgProduitFixtures\u003A\u003AgetGroups\u0028\u0029",
            "name": "getGroups",
            "summary": "D\u00E9finit\u0020le\u0020groupe\u0020de\u0020fixtures\u0020auquel\u0020appartient\u0020cette\u0020classe.",
            "url": "classes/App-DataFixtures-UpdateImgProduitFixtures.html#method_getGroups"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur",
            "name": "Distributeur",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020un\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020de\u0020l\u0027entit\u00E9\u0020Distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020unique\u0020du\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003AgetNom\u0028\u0029",
            "name": "getNom",
            "summary": "Retourne\u0020le\u0020nom\u0020du\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method_getNom"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003AsetNom\u0028\u0029",
            "name": "setNom",
            "summary": "D\u00E9finit\u0020le\u0020nom\u0020du\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method_setNom"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003AgetProduits\u0028\u0029",
            "name": "getProduits",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020produits\u0020associ\u00E9s\u0020au\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method_getProduits"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003AaddProduit\u0028\u0029",
            "name": "addProduit",
            "summary": "Ajoute\u0020un\u0020produit\u0020au\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method_addProduit"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003AremoveProduit\u0028\u0029",
            "name": "removeProduit",
            "summary": "Supprime\u0020un\u0020produit\u0020associ\u00E9\u0020au\u0020distributeur.",
            "url": "classes/App-Entity-Distributeur.html#method_removeProduit"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Distributeur.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003A\u0024produits",
            "name": "produits",
            "summary": "",
            "url": "classes/App-Entity-Distributeur.html#property_produits"
        },                {
            "fqsen": "\\App\\Entity\\Distributeur\u003A\u003A\u0024nom",
            "name": "nom",
            "summary": "",
            "url": "classes/App-Entity-Distributeur.html#property_nom"
        },                {
            "fqsen": "\\App\\Entity\\Produit",
            "name": "Produit",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020un\u0020produit.",
            "url": "classes/App-Entity-Produit.html"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AisPrixQuantiteValid\u0028\u0029",
            "name": "isPrixQuantiteValid",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#method_isPrixQuantiteValid"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AisContentValid\u0028\u0029",
            "name": "isContentValid",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#method_isContentValid"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020de\u0020l\u0027entit\u00E9\u0020Produit.",
            "url": "classes/App-Entity-Produit.html#method___construct"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetNom\u0028\u0029",
            "name": "getNom",
            "summary": "Retourne\u0020le\u0020nom\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_getNom"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AsetNom\u0028\u0029",
            "name": "setNom",
            "summary": "D\u00E9finit\u0020le\u0020nom\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_setNom"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetPrix\u0028\u0029",
            "name": "getPrix",
            "summary": "Retourne\u0020le\u0020prix\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_getPrix"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AsetPrix\u0028\u0029",
            "name": "setPrix",
            "summary": "D\u00E9finit\u0020le\u0020prix\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_setPrix"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetQuantite\u0028\u0029",
            "name": "getQuantite",
            "summary": "Retourne\u0020la\u0020quantit\u00E9\u0020disponible.",
            "url": "classes/App-Entity-Produit.html#method_getQuantite"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AsetQuantite\u0028\u0029",
            "name": "setQuantite",
            "summary": "D\u00E9finit\u0020la\u0020quantit\u00E9\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_setQuantite"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AisRupture\u0028\u0029",
            "name": "isRupture",
            "summary": "Indique\u0020si\u0020le\u0020produit\u0020est\u0020en\u0020rupture\u0020de\u0020stock.",
            "url": "classes/App-Entity-Produit.html#method_isRupture"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AsetRupture\u0028\u0029",
            "name": "setRupture",
            "summary": "D\u00E9finit\u0020l\u0027\u00E9tat\u0020de\u0020rupture\u0020de\u0020stock.",
            "url": "classes/App-Entity-Produit.html#method_setRupture"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetLienImage\u0028\u0029",
            "name": "getLienImage",
            "summary": "Retourne\u0020le\u0020lien\u0020de\u0020l\u0027image\u0020associ\u00E9e\u0020au\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_getLienImage"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AsetLienImage\u0028\u0029",
            "name": "setLienImage",
            "summary": "D\u00E9finit\u0020le\u0020lien\u0020de\u0020l\u0027image\u0020associ\u00E9e\u0020au\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_setLienImage"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetReference\u0028\u0029",
            "name": "getReference",
            "summary": "Retourne\u0020la\u0020r\u00E9f\u00E9rence\u0020associ\u00E9e\u0020au\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_getReference"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AsetReference\u0028\u0029",
            "name": "setReference",
            "summary": "D\u00E9finit\u0020la\u0020r\u00E9f\u00E9rence\u0020associ\u00E9e\u0020au\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_setReference"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AgetDistributeurs\u0028\u0029",
            "name": "getDistributeurs",
            "summary": "Retourne\u0020la\u0020liste\u0020des\u0020distributeurs\u0020associ\u00E9s\u0020au\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_getDistributeurs"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AaddDistributeur\u0028\u0029",
            "name": "addDistributeur",
            "summary": "Ajoute\u0020un\u0020distributeur\u0020\u00E0\u0020la\u0020liste\u0020des\u0020distributeurs\u0020du\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_addDistributeur"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003AremoveDistributeur\u0028\u0029",
            "name": "removeDistributeur",
            "summary": "Supprime\u0020un\u0020distributeur\u0020associ\u00E9\u0020au\u0020produit.",
            "url": "classes/App-Entity-Produit.html#method_removeDistributeur"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024nom",
            "name": "nom",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_nom"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024prix",
            "name": "prix",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_prix"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024quantite",
            "name": "quantite",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_quantite"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024rupture",
            "name": "rupture",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_rupture"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024lienImage",
            "name": "lienImage",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_lienImage"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024reference",
            "name": "reference",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_reference"
        },                {
            "fqsen": "\\App\\Entity\\Produit\u003A\u003A\u0024distributeurs",
            "name": "distributeurs",
            "summary": "",
            "url": "classes/App-Entity-Produit.html#property_distributeurs"
        },                {
            "fqsen": "\\App\\Entity\\Reference",
            "name": "Reference",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020une\u0020r\u00E9f\u00E9rence\u0020de\u0020produit.",
            "url": "classes/App-Entity-Reference.html"
        },                {
            "fqsen": "\\App\\Entity\\Reference\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020unique\u0020de\u0020la\u0020r\u00E9f\u00E9rence.",
            "url": "classes/App-Entity-Reference.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\Reference\u003A\u003AgetNumero\u0028\u0029",
            "name": "getNumero",
            "summary": "Retourne\u0020le\u0020num\u00E9ro\u0020de\u0020la\u0020r\u00E9f\u00E9rence.",
            "url": "classes/App-Entity-Reference.html#method_getNumero"
        },                {
            "fqsen": "\\App\\Entity\\Reference\u003A\u003AsetNumero\u0028\u0029",
            "name": "setNumero",
            "summary": "D\u00E9finit\u0020le\u0020num\u00E9ro\u0020de\u0020la\u0020r\u00E9f\u00E9rence.",
            "url": "classes/App-Entity-Reference.html#method_setNumero"
        },                {
            "fqsen": "\\App\\Entity\\Reference\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-Reference.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\Reference\u003A\u003A\u0024numero",
            "name": "numero",
            "summary": "",
            "url": "classes/App-Entity-Reference.html#property_numero"
        },                {
            "fqsen": "\\App\\Entity\\User",
            "name": "User",
            "summary": "Entit\u00E9\u0020repr\u00E9sentant\u0020un\u0020utilisateur.",
            "url": "classes/App-Entity-User.html"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Retourne\u0020l\u0027identifiant\u0020unique\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "Retourne\u0020le\u0020nom\u0020d\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "D\u00E9finit\u0020le\u0020nom\u0020d\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetUserIdentifier\u0028\u0029",
            "name": "getUserIdentifier",
            "summary": "Retourne\u0020l\u0027identifiant\u0020utilis\u00E9\u0020pour\u0020l\u0027authentification.",
            "url": "classes/App-Entity-User.html#method_getUserIdentifier"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetRoles\u0028\u0029",
            "name": "getRoles",
            "summary": "Retourne\u0020les\u0020r\u00F4les\u0020attribu\u00E9s\u0020\u00E0\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_getRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetRoles\u0028\u0029",
            "name": "setRoles",
            "summary": "D\u00E9finit\u0020les\u0020r\u00F4les\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_setRoles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Retourne\u0020le\u0020mot\u0020de\u0020passe\u0020chiffr\u00E9\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "D\u00E9finit\u0020le\u0020mot\u0020de\u0020passe\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A__serialize\u0028\u0029",
            "name": "__serialize",
            "summary": "S\u00E9rialise\u0020les\u0020donn\u00E9es\u0020de\u0020l\u0027utilisateur\u0020pour\u0020la\u0020session.",
            "url": "classes/App-Entity-User.html#method___serialize"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AeraseCredentials\u0028\u0029",
            "name": "eraseCredentials",
            "summary": "Supprime\u0020les\u0020informations\u0020sensibles\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_eraseCredentials"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AgetApiToken\u0028\u0029",
            "name": "getApiToken",
            "summary": "Retourne\u0020le\u0020token\u0020API\u0020associ\u00E9\u0020\u00E0\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_getApiToken"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003AsetApiToken\u0028\u0029",
            "name": "setApiToken",
            "summary": "D\u00E9finit\u0020le\u0020token\u0020API\u0020de\u0020l\u0027utilisateur.",
            "url": "classes/App-Entity-User.html#method_setApiToken"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024apiToken",
            "name": "apiToken",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_apiToken"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024roles",
            "name": "roles",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_roles"
        },                {
            "fqsen": "\\App\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Form\\DistributeurType",
            "name": "DistributeurType",
            "summary": "Classe\u0020repr\u00E9sentant\u0020le\u0020formulaire\u0020de\u0020cr\u00E9ation\nou\u0020de\u0020modification\u0020d\u0027un\u0020produit.",
            "url": "classes/App-Form-DistributeurType.html"
        },                {
            "fqsen": "\\App\\Form\\DistributeurType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construit\u0020le\u0020formulaire\u0020associ\u00E9\u0020\u00E0\u0020l\u0027entit\u00E9\u0020Distributeur.",
            "url": "classes/App-Form-DistributeurType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\DistributeurType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configure\u0020les\u0020options\u0020par\u0020d\u00E9faut\u0020du\u0020formulaire.",
            "url": "classes/App-Form-DistributeurType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\ProduitType",
            "name": "ProduitType",
            "summary": "Classe\u0020repr\u00E9sentant\u0020le\u0020formulaire\u0020de\u0020cr\u00E9ation\nou\u0020de\u0020modification\u0020d\u0027un\u0020produit.",
            "url": "classes/App-Form-ProduitType.html"
        },                {
            "fqsen": "\\App\\Form\\ProduitType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "Construit\u0020le\u0020formulaire\u0020associ\u00E9\u0020\u00E0\u0020l\u0027entit\u00E9\u0020Produit.",
            "url": "classes/App-Form-ProduitType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\ProduitType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configure\u0020les\u0020options\u0020du\u0020formulaire.",
            "url": "classes/App-Form-ProduitType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\ReferenceType",
            "name": "ReferenceType",
            "summary": "Classe\u0020repr\u00E9sentant\u0020le\u0020formulaire\u0020de\u0020cr\u00E9ation\nou\u0020de\u0020modification\u0020d\u0027un\u0020produit.",
            "url": "classes/App-Form-ReferenceType.html"
        },                {
            "fqsen": "\\App\\Form\\ReferenceType\u003A\u003AbuildForm\u0028\u0029",
            "name": "buildForm",
            "summary": "M\u00E9thode\u0020permettant\u0020de\u0020construire\u0020le\u0020formulaire.",
            "url": "classes/App-Form-ReferenceType.html#method_buildForm"
        },                {
            "fqsen": "\\App\\Form\\ReferenceType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "Configure\u0020les\u0020options\u0020du\u0020formulaire.",
            "url": "classes/App-Form-ReferenceType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\Type\\MyCheckboxType",
            "name": "MyCheckboxType",
            "summary": "Classe\u0020repr\u00E9sentant\u0020le\u0020formulaire\u0020de\u0020cr\u00E9ation\nou\u0020de\u0020modification\u0020d\u0027un\u0020produit.",
            "url": "classes/App-Form-Type-MyCheckboxType.html"
        },                {
            "fqsen": "\\App\\Form\\Type\\MyCheckboxType\u003A\u003AconfigureOptions\u0028\u0029",
            "name": "configureOptions",
            "summary": "",
            "url": "classes/App-Form-Type-MyCheckboxType.html#method_configureOptions"
        },                {
            "fqsen": "\\App\\Form\\Type\\MyCheckboxType\u003A\u003AgetParent\u0028\u0029",
            "name": "getParent",
            "summary": "",
            "url": "classes/App-Form-Type-MyCheckboxType.html#method_getParent"
        },                {
            "fqsen": "\\App\\Kernel",
            "name": "Kernel",
            "summary": "Classe\u0020Kernel\u0020de\u0020l\u0027application\u0020Symfony.",
            "url": "classes/App-Kernel.html"
        },                {
            "fqsen": "\\App\\Repository\\DistributeurRepository",
            "name": "DistributeurRepository",
            "summary": "Repository\u0020de\u0020l\u0027entit\u00E9\u0020Distributeur.",
            "url": "classes/App-Repository-DistributeurRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\DistributeurRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository.",
            "url": "classes/App-Repository-DistributeurRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ProduitRepository",
            "name": "ProduitRepository",
            "summary": "Repository\u0020de\u0020l\u0027entit\u00E9\u0020Produit.",
            "url": "classes/App-Repository-ProduitRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\ProduitRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository\u0020Produit.",
            "url": "classes/App-Repository-ProduitRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\ProduitRepository\u003A\u003AorderingProduit\u0028\u0029",
            "name": "orderingProduit",
            "summary": "R\u00E9cup\u00E8re\u0020la\u0020liste\u0020des\u0020produits\u0020tri\u00E9s\u0020par\u0020identifiant\u0020d\u00E9croissant.",
            "url": "classes/App-Repository-ProduitRepository.html#method_orderingProduit"
        },                {
            "fqsen": "\\App\\Repository\\ProduitRepository\u003A\u003AgetLastProduit\u0028\u0029",
            "name": "getLastProduit",
            "summary": "R\u00E9cup\u00E8re\u0020le\u0020dernier\u0020produit\u0020ajout\u00E9\u0020dans\u0020la\u0020base\u0020de\u0020donn\u00E9es.",
            "url": "classes/App-Repository-ProduitRepository.html#method_getLastProduit"
        },                {
            "fqsen": "\\App\\Repository\\ReferenceRepository",
            "name": "ReferenceRepository",
            "summary": "Repository\u0020de\u0020l\u0027entit\u00E9\u0020Reference.",
            "url": "classes/App-Repository-ReferenceRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\ReferenceRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository\u0020Reference.",
            "url": "classes/App-Repository-ReferenceRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository",
            "name": "UserRepository",
            "summary": "Repository\u0020permettant\u0020de\u0020g\u00E9rer\u0020les\u0020utilisateurs.",
            "url": "classes/App-Repository-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020repository\u0020User.",
            "url": "classes/App-Repository-UserRepository.html#method___construct"
        },                {
            "fqsen": "\\App\\Repository\\UserRepository\u003A\u003AupgradePassword\u0028\u0029",
            "name": "upgradePassword",
            "summary": "Met\u0020\u00E0\u0020jour\u0020automatiquement\u0020le\u0020mot\u0020de\u0020passe\u0020d\u0027un\u0020utilisateur.",
            "url": "classes/App-Repository-UserRepository.html#method_upgradePassword"
        },                {
            "fqsen": "\\App\\Security\\AccessDeniedHandler",
            "name": "AccessDeniedHandler",
            "summary": "Gestionnaire\u0020personnalis\u00E9\u0020d\u0027acc\u00E8s\u0020refus\u00E9.",
            "url": "classes/App-Security-AccessDeniedHandler.html"
        },                {
            "fqsen": "\\App\\Security\\AccessDeniedHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "G\u00E8re\u0020les\u0020acc\u00E8s\u0020refus\u00E9s\u0020dans\u0020l\u0027application.",
            "url": "classes/App-Security-AccessDeniedHandler.html#method_handle"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator",
            "name": "ApiKeyAuthenticator",
            "summary": "Authenticator\u0020Symfony\u0020permettant\u0020de\u0020s\u00E9curiser\u0020une\u0020API\u0020via\u0020un\u0020token.",
            "url": "classes/App-Security-ApiKeyAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator\u003A\u003Asupports\u0028\u0029",
            "name": "supports",
            "summary": "D\u00E9termine\u0020si\u0020cet\u0020authenticator\u0020doit\u0020\u00EAtre\u0020utilis\u00E9\u0020pour\u0020la\u0020requ\u00EAte.",
            "url": "classes/App-Security-ApiKeyAuthenticator.html#method_supports"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020de\u0020l\u0027authenticator.",
            "url": "classes/App-Security-ApiKeyAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Authentifie\u0020la\u0020requ\u00EAte\u0020en\u0020utilisant\u0020le\u0020token\u0020API\u0020fourni\u0020dans\u0020le\u0020header.",
            "url": "classes/App-Security-ApiKeyAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "M\u00E9thode\u0020appel\u00E9e\u0020lorsque\u0020l\u0027authentification\u0020r\u00E9ussit.",
            "url": "classes/App-Security-ApiKeyAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator\u003A\u003AonAuthenticationFailure\u0028\u0029",
            "name": "onAuthenticationFailure",
            "summary": "M\u00E9thode\u0020appel\u00E9e\u0020lorsque\u0020l\u0027authentification\u0020\u00E9choue.",
            "url": "classes/App-Security-ApiKeyAuthenticator.html#method_onAuthenticationFailure"
        },                {
            "fqsen": "\\App\\Security\\ApiKeyAuthenticator\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Security-ApiKeyAuthenticator.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator",
            "name": "CustomAuthenticator",
            "summary": "Authenticator\u0020personnalis\u00E9\u0020pour\u0020g\u00E9rer\u0020la\u0020connexion\u0020via\u0020un\u0020formulaire.",
            "url": "classes/App-Security-CustomAuthenticator.html"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020de\u0020l\u0027authenticator.",
            "url": "classes/App-Security-CustomAuthenticator.html#method___construct"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "M\u00E9thode\u0020appel\u00E9e\u0020lors\u0020de\u0020la\u0020tentative\u0020d\u0027authentification.",
            "url": "classes/App-Security-CustomAuthenticator.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator\u003A\u003AonAuthenticationSuccess\u0028\u0029",
            "name": "onAuthenticationSuccess",
            "summary": "M\u00E9thode\u0020appel\u00E9e\u0020lorsque\u0020l\u0027authentification\u0020r\u00E9ussit.",
            "url": "classes/App-Security-CustomAuthenticator.html#method_onAuthenticationSuccess"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator\u003A\u003AgetLoginUrl\u0028\u0029",
            "name": "getLoginUrl",
            "summary": "Retourne\u0020l\u0027URL\u0020de\u0020la\u0020page\u0020de\u0020connexion.",
            "url": "classes/App-Security-CustomAuthenticator.html#method_getLoginUrl"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator\u003A\u003ALOGIN_ROUTE",
            "name": "LOGIN_ROUTE",
            "summary": "Route\u0020utilis\u00E9e\u0020pour\u0020afficher\u0020la\u0020page\u0020de\u0020connexion.",
            "url": "classes/App-Security-CustomAuthenticator.html#constant_LOGIN_ROUTE"
        },                {
            "fqsen": "\\App\\Security\\CustomAuthenticator\u003A\u003A\u0024urlGenerator",
            "name": "urlGenerator",
            "summary": "",
            "url": "classes/App-Security-CustomAuthenticator.html#property_urlGenerator"
        },                {
            "fqsen": "\\App\\Service\\MessageGenerator",
            "name": "MessageGenerator",
            "summary": "Service\u0020permettant\u0020de\u0020g\u00E9n\u00E9rer\u0020des\u0020messages.",
            "url": "classes/App-Service-MessageGenerator.html"
        },                {
            "fqsen": "\\App\\Service\\MessageGenerator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructeur\u0020du\u0020service\u0020MessageGenerator.",
            "url": "classes/App-Service-MessageGenerator.html#method___construct"
        },                {
            "fqsen": "\\App\\Service\\MessageGenerator\u003A\u003AgetHappyMessage\u0028\u0029",
            "name": "getHappyMessage",
            "summary": "G\u00E9n\u00E8re\u0020un\u0020message\u0020al\u00E9atoire\u0020positif.",
            "url": "classes/App-Service-MessageGenerator.html#method_getHappyMessage"
        },                {
            "fqsen": "\\App\\Validator\\Antispam",
            "name": "Antispam",
            "summary": "Classe\u0020repr\u00E9sentant\u0020une\u0020contrainte\u0020de\u0020validation\u0020Antispam.",
            "url": "classes/App-Validator-Antispam.html"
        },                {
            "fqsen": "\\App\\Validator\\Antispam\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/App-Validator-Antispam.html#property_message"
        },                {
            "fqsen": "\\App\\Validator\\AntispamValidator",
            "name": "AntispamValidator",
            "summary": "Validateur\u0020associ\u00E9\u0020\u00E0\u0020la\u0020contrainte\u0020Antispam.",
            "url": "classes/App-Validator-AntispamValidator.html"
        },                {
            "fqsen": "\\App\\Validator\\AntispamValidator\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Valide\u0020qu\u0027un\u0020message\u0020ne\u0020contient\u0020pas\u0020de\u0020spam.",
            "url": "classes/App-Validator-AntispamValidator.html#method_validate"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Data",
            "name": "Data",
            "summary": "",
            "url": "namespaces/app-data.html"
        },                {
            "fqsen": "\\App\\DataFixtures",
            "name": "DataFixtures",
            "summary": "",
            "url": "namespaces/app-datafixtures.html"
        },                {
            "fqsen": "\\App\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-entity.html"
        },                {
            "fqsen": "\\App\\Form",
            "name": "Form",
            "summary": "",
            "url": "namespaces/app-form.html"
        },                {
            "fqsen": "\\App\\Form\\Type",
            "name": "Type",
            "summary": "",
            "url": "namespaces/app-form-type.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "namespaces/app-repository.html"
        },                {
            "fqsen": "\\App\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-security.html"
        },                {
            "fqsen": "\\App\\Service",
            "name": "Service",
            "summary": "",
            "url": "namespaces/app-service.html"
        },                {
            "fqsen": "\\App\\Validator",
            "name": "Validator",
            "summary": "",
            "url": "namespaces/app-validator.html"
        }            ]
);
